cookbook/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.conf.urls import url
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('frontend.urls')),
    url(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frontend/urls.py
from django.urls import path
from . import views
app_name="frontend"
urlpatterns = [
    path('',views.index,name="home"),
    path("singlepage/<int:id>",views.singlepage,name="singlepage"),
    path("category/<str:category>",views.category,name="category"),
    path("aboutus",views.aboutus,name="aboutus"),
    path("search",views.search,name="search"),
    path("subscribe",views.subscribe,name="subscribe"),
    path("contact",views.contact,name="contact"),
    path("addquery",views.addquery,name="addquery"),
    path("recipies",views.recipies,name="recipies"),
    path("sendemail",views.sendemail,name="sendemail"),
]

frontend/models.py
from datetime import datetime
from tabnanny import verbose
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.

#recipe post
class Recipe(models.Model):
    title = models.CharField(max_length=200)
    category = models.CharField(max_length=200)
    description = models.TextField()
    slug = models.SlugField()
    premium = models.BooleanField(default=False)
    image = models.ImageField(blank=True, upload_to='recipe_images')
    publish = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User,on_delete=models.CASCADE,related_name='recipe_posts')
    def __str__(self):
        return self.title
    
class NavigationMenu(models.Model):
    title = models.CharField(max_length=50)
    link  = models.CharField(max_length=50)
    status = models.BooleanField(default=True)
    def __str__(self):
        return self.title
    
class SocialMedia(models.Model):
    title = models.CharField(max_length=50)
    link  = models.CharField(max_length=200)
    icons = models.CharField(max_length=150)
    disable = models.BooleanField(default=False)
    def __str__(self):
        return self.title

class Contact(models.Model):
    address = models.TextField()
    phone = models.BigIntegerField()
    email = models.CharField(max_length=200)
    support = models.CharField(max_length=200)
    location = models.CharField(max_length=200,blank=True)
    hours = models.CharField(max_length=200,blank=True)
    def __str__(self):
        return self.email

class BannerManegment(models.Model):
    title = models.CharField(max_length=50)
    banner_image = models.ImageField(blank=True, upload_to="banner")
    status = models.BooleanField(default=True)
    navigationid = models.OneToOneField(NavigationMenu, verbose_name="Navigation ID", on_delete=models.CASCADE)
    def __str__(self):
        return self.title
    
class ProfileSettings(models.Model):
    phone = models.BigIntegerField(max_length=20)
    user = models.OneToOneField(User,on_delete=models.CASCADE,verbose_name="User Name")
    user_photo = models.ImageField(upload_to="userimages",verbose_name="User Picture")
    bio = models.TextField(verbose_name="User Bio Data")
    def __str__(self):
        return self.user.username
class Subscribe(models.Model):
    status = models.BooleanField(default=True,verbose_name="Disable")
    email = models.CharField(max_length=100,verbose_name="Subscribe Email")
    def __str__(self):
        return self.email

class Ads(models.Model):
    ads_link =models.CharField(max_length=200,verbose_name="Ads Link")
    ads_created = models.DateTimeField(default=datetime.now(),verbose_name="Ads Created Date")
    status = models.BooleanField(default=False,verbose_name="Disable")
    ads_title = models.CharField(max_length=200,verbose_name="Ads Title")
    ads_image = models.ImageField(verbose_name="Ads Image",upload_to="ads")
    def __str__(self):
        return self.ads_title

class Bloginfo(models.Model):
    blog_title = models.CharField(max_length=150,verbose_name="title")
    blog_icon  = models.CharField(max_length=100,verbose_name="icon")
    blog_description = models.TextField(verbose_name="blog description")
    def __str__(self):
        return self.blog_title

class FooterMenu(models.Model):
    menu_title = models.CharField(max_length=100,verbose_name="title")
    menu_link = models.CharField(max_length=100,verbose_name="link")
    menu_status = models.BooleanField(default=False,verbose_name="Disable")
    def __str__(self):
        return self.menu_title

class Enquiry(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField()
    subject = models.CharField(max_length=200)
    phone = models.BigIntegerField()
    message = models.TextField()
    def __str__(self):
        return self.subject
    
    
    
    
    

frontend/views.py
from django.contrib import messages
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import *
from django.contrib import messages
from django.db.models import Count
from django.core.paginator import Paginator 
from django.db.models import Q
from django.http import JsonResponse
from django.conf import settings
from django.core.mail import send_mail

#home page index loading
def commondata():
    navigation_menu = NavigationMenu.objects.filter(status=True).all() 
    contacts = Contact.objects.get()
    social_media = SocialMedia.objects.filter(disable=False).all()
    bloginfo = Bloginfo.objects.get()
    footermenu = FooterMenu.objects.all()
    data = {
        "navigation":navigation_menu,
        "contacts":contacts,
        "socialmedia":social_media,
        "bloginfo":bloginfo,
        "footermenu":footermenu
    } 
    return data
def index(request):
    record = Recipe.objects.filter(premium=True).all().order_by('-id')
    recentpost = Recipe.objects.all().order_by('-id')[:5]
    posts = Recipe.objects.all()[:8]
    userinfo = User.objects.filter(is_superuser=True).all()[0]
    userid = userinfo.id
    userinfo = ProfileSettings.objects.select_related("user").get(id=userid)
    common  = commondata()
    ads = Ads.objects.order_by("?").first()
    categories = Recipe.objects.values("category").annotate(Count('category')).distinct()
    data = {
        "record":record,
        "recent_post":recentpost,
        "posts":posts,
        "categories":categories,
        "userinfo":userinfo,
        "ads":ads
    }
    data.update(common)
    return render(request,'frontend/index.html',data)

def singlepage(request,id):
    record = Recipe.objects.get(id=id)
    data = {
        "record" :record
    }
    data.update(commondata())
    return render(request,'frontend/singlepage.html',data)

def category(request,category):
    
    record = Recipe.objects.filter(category=category).all()
    book_paginator = Paginator(record,4)

    page_num = request.GET.get('page')
    
    page = book_paginator.get_page(page_num)

    context = {
        'count' : book_paginator.count,
        'records' : page
    }
    context.update(commondata())
    return render(request, 'frontend/category.html', context)

def aboutus(request):
    return render(request,'frontend/about.html')

def search(request):
    param = request.GET.get('q')
    if param:
        posts = Recipe.objects.filter(Q(title__icontains=param) | Q(description__icontains=param) | Q(category__icontains=param) )
        book_paginator = Paginator(posts,4)

        page_num = request.GET.get('page')
    
        page = book_paginator.get_page(page_num)

    context = {
        'count' : book_paginator.count,
        'records' : page,
         "query" :"/search?q={0}".format(param)
    }
    context.update(commondata())
    return render(request,'frontend/search.html',context)

def subscribe(request):
        email_id = request.POST.get("email_id")
        subscribe = Subscribe()
        subscribe.email = email_id
        subscribe.save()
        if(Subscribe.objects.latest('id').id>0):
            response = {'msg':'SubScribed' }
        else:
            response = {' msg':'Failed' }
        return JsonResponse(response)
        
def contact(request):
    data = commondata()
    return render(request,'frontend/contact.html',data)

def addquery(request):
   enquiry  = Enquiry()
   enquiry.name = request.POST.get("name")
   enquiry.email = request.POST.get("email")
   enquiry.subject = request.POST.get("subject")
   enquiry.phone = request.POST.get("phone")
   enquiry.message = request.POST.get("message")
   enquiry.save()
   response = redirect('/contact')
   messages.add_message(request,messages.SUCCESS,"Message Send")
   return(response)

def recipies(request):
    record = Recipe.objects.all()
    book_paginator = Paginator(record,6)

    page_num = request.GET.get('page')
    
    page = book_paginator.get_page(page_num)

    context = {
        'count' : book_paginator.count,
        'records' : page,
        "url":'/recipies'
    }
    context.update(commondata())
    return render(request,'frontend/recipies.html',context)
def sendemail(request):
    send_mail(
            subject="test",
            message="test",
            from_email="hithindevelopertester@gmail.com",
            recipient_list=["hithindeveloper@gmail.com"],
            fail_silently = False,
        )
   

templates/frontend/category.html
{% load static  %}
<!doctype html>
<html lang="en">
    {% include 'frontend/head.html' %}

<body>
    {% include 'frontend/navigation.html' %}
    <!-- inner banner -->
    <section class="inner-banner py-5">
        <div class="w3l-breadcrumb py-lg-5">
            <div class="container pt-sm-5 pt-4 pb-sm-4">
                <h4 class="inner-text-title font-weight-bold pt-5">About Us</h4>
                <ul class="breadcrumbs-custom-path">
                    <li><a href="index.html">Home</a></li>
                    <li class="active"><span class="fa fa-chevron-right mx-2" aria-hidden="true"></span>About</li>
                </ul>
            </div>
        </div>
    </section>

    <section class="about-section ">
        <div class="container py-md-5 ">
            
            <div class="row">
            {% for item in records %}
                <div class="col-sm-6 card mt-lg-5 mt-4 ">
                    <div class="card-header p-0 position-relative border-0">
                        <a href="{% url "frontend:singlepage" item.id %}">
                            <img class="card-img-bottom d-block radius-image" src="{{item.image.url}}" alt="Card image cap">
                        </a>
                        <a href="{% url "frontend:singlepage" item.id %}" class="category-style">{{ item.category }}</a>
                    </div>
                    <div class="title-wrap title-wrap-2">
                        <h4 class="title"><a href="blog-single.html">{{item.title}} </a></h4>
                        <ul class="admin-list mt-2 mb-4" style="display:none !important">
                            <li><a href="blog-single.html"><i class="far fa-user"></i>Patty Joe
                                </a></li>
                            <li><a href="blog-single.html"><i class="far fa-heart"></i>18 Likes</a></li>
                            <li><a href="blog-single.html"><i class="far fa-comment-dots"></i>8 Comments</a>
                            </li>
                        </ul>
                        <p>
                            {{ item.description | slice:":200" }}
                            <a href ="{% url "frontend:singlepage" item.id %}" class="btn btn-style">Read More</a>
                        </p>
                    </div>
                </div>
            {% endfor %}
            
            </div>
            <nav class=" navigation mt-3 ">
                {% if records.has_other_pages %}
                <ul class="pagination">
                  {% if records.has_previous %}
                    <li class="page-item"><a class="page-link"  href="?page={{ records.previous_page_number }}">Prev</a></li>
                  {% else %}
                    <li class="disabled"><span class="page-link">Previous</span></li>
                  {% endif %}
                  {% for i in records.paginator.page_range %}
                    {% if records.number == i %}
                      <li class="page-item active"><span class="page-link" >{{ i }} <span class="sr-only">(current)</span></span></li>
                    {% else %}
                      <li class="page-item"><a class="page-link"  href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                  {% endfor %}
                  {% if records.has_next %}
                    <li class="page-item"><a class="page-link"  href="?page={{ records.next_page_number }}">Next</a></li>
                  {% else %}
                    <li class="page-item disabled"><span class="page-link" >Last</span></li>
                  {% endif %}
                </ul>
              {% endif %}
            </nav>
        </div>
    </section>
   

   
        <div class="container" style="display:none !important">
            <h3 class="title-style text-center mb-lg-5 mb-4">Our Amazing Chef's</h3>
            <div class="row">

            </div>


        </div>

  
 

    {% include 'frontend/footer.html' %}
    <button onclick="topFunction()" id="movetop" title="Go to top">
        <span class="fas fa-level-up-alt" aria-hidden="true"></span>
    </button>
    {% include 'frontend/footerscript.html' %}
</body>

</html>

templates/frontend/contact.html
{% load static  %}
<!doctype html>
<html lang="en">
    {% include 'frontend/head.html' %}

<body>
    {% include 'frontend/navigation.html' %}
    <!-- inner banner -->
    <section class="inner-banner py-5">
        <div class="w3l-breadcrumb py-lg-5">
            <div class="container pt-sm-5 pt-4 pb-sm-4">
                <h4 class="inner-text-title font-weight-bold pt-5">About Us</h4>
                <ul class="breadcrumbs-custom-path">
                    <li><a href="index.html">Home</a></li>
                    <li class="active"><span class="fa fa-chevron-right mx-2" aria-hidden="true"></span>About</li>
                </ul>
            </div>
        </div>
    </section>

    <section class="about-section ">
        <div class="container py-md-5 ">
            
            <div class="row">
                <form method="post" class="col-md-12 col-sm-12 col-xl-12 col-lg-12" action="{% url 'frontend:addquery' %}" enctype="multipart/form-data">
                    <div class="form-group-lg">
                      <label for="exampleInputEmail1">Name</label>
                      {% csrf_token %}
                      <input type="text" name="name" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">email</label>
                        <input type="text" name="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                      </div>

                      <div class="form-group">
                        <label for="exampleInputEmail1">phone</label>
                        <input type="text" name="phone" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                      </div>


                    <div class="form-group">
                      <label for="exampleInputPassword1">Subject</label>
                      <input type="text" name="subject" class="form-control" id="exampleInputPassword1">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">message</label>
                        <textarea name="message" class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>

                    </div>

                    <button type="submit" class="btn btn-primary">Submit</button>
                    {% if messages %} {% for message in messages %} {{ message }} {% endfor %}
                    {% endif %}
                  </form>
            </div>
            
        </div>
    </section>
   

   
        <div class="container" style="display:none !important">
            <h3 class="title-style text-center mb-lg-5 mb-4">Our Amazing Chef's</h3>
            <div class="row">

            </div>


        </div>

  
 

    {% include 'frontend/footer.html' %}
    <button onclick="topFunction()" id="movetop" title="Go to top">
        <span class="fas fa-level-up-alt" aria-hidden="true"></span>
    </button>
    {% include 'frontend/footerscript.html' %}
</body>

</html>

templates/frontend/index.html
<!-- https://www.angularjswiki.com/fontawesome/arrows/ -->
{% load static %}
<!doctype html>
<html lang="en">
{% include 'frontend/head.html' %}
<body>

    {% include 'frontend/navigation.html' %}
    
    <!-- banner blog section -->
    <section class="w3l-banner-blog py-5">
        <div class="w3l-main-blog py-4">
            <div class="owl-blog owl-carousel owl-theme">
               
                {% for recipe in record %}
               
                <div class="item">
                    <div class="news-img">
                        <a href="{% url "frontend:singlepage" recipe.id %}"><img src="{{ recipe.image }}" class="img-fluid img-responsive"
                                alt="news image"></a>
                        <div class="title-wrap">
                            <h4 class="title">
                                
                                <a href="{% url "frontend:singlepage" recipe.id %}">{{ recipe.title }}</a>
                            </h4>
                            <ul class="admin-list mt-2 mb-4" style="display:none !important;">
                                <li><a href="#blog"><i class="far fa-user"></i>Olive Yew
                                    </a></li>
                                <li><a href="#blog"><i class="far fa-heart"></i>18 Likes</a></li>
                                <li><a href="#blog"><i class="far fa-comment-dots"></i>8 Comments</a>
                                </li>
                            </ul>
                            <p>
                                {{ recipe.description | slice:":200" }}
                                <a href ="{% url "frontend:singlepage" recipe.id %}" class="btn btn-style">Read More</a>
                            </p>
                        </div>
                    </div>
                </div>
               {% endfor %}
                
            </div>
        </div>
    </section>
  
    <!-- bg with video icon -->
    <section class="w3l-covers-14 pt-5">
        <div class="container pt-md-5 pt-4">
            <div class="blog-play-w3 text-center py-5">
                <div class="mx-auto py-5 px-4" style="max-width:450px;">
                    <h3 class="title-style text-white">We don't just cook, we thread you to delicacies...</h3>
                    <ul class="admin-list mt-4 mb-4">
                        <li><a href="#blog" class="text-white"><i class="far fa-user"></i>Eety Cru
                            </a></li>
                        <li><a href="#blog" class="text-white"><i class="far fa-heart"></i>10 Likes</a></li>
                        <li><a href="#blog" class="text-white"><i class="far fa-comment-dots"></i>9
                                Comments</a>
                        </li>
                    </ul>
                    <div class="video-section mt-5 pt-4 pb-5">
                        <!--//video-->
                        <a href="#small-dialog" class="popup-with-zoom-anim play-view text-center pl-3">
                            <span class="video-play-icon">
                                <span class="fas fa-play"></span>
                            </span>
                        </a>
                        <!-- dialog itself, mfp-hide class is required to make dialog hidden -->
                        <div id="small-dialog" class="zoom-anim-dialog mfp-hide">
                             <iframe src="https://player.vimeo.com/video/192089758" frameborder="0"
                                allow="autoplay; fullscreen" allowfullscreen></iframe> 
                                {% comment %} <iframe   allowfullscreen src="https://www.youtube.com/embed/lRfPUSz7tdU" title="BIRYANI | MUTTON BIRYANI with Eggs | Traditional Biryani Recipe cooking in Village | Village Cooking" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe> {% endcomment %}
                            </div>
                        <!--//video-->
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- //bg with video icon -->

    <!-- blog page -->
    <section class="w3l-text-11 py-5">
        <div class="container py-md-5 py-4">
            <div class="row">
                <div class="col-lg-8 text11-content">
                    <div class="row">
                  


                        {% for post in posts %}
                        <div class="col-sm-6 card mt-lg-5 mt-4">
                            <div class="card-header p-0 position-relative border-0">
                                <a href="{% url "frontend:singlepage" post.id %}">
                                    <img class="card-img-bottom d-block radius-image" src="{{post.image}}"
                                        alt="Card image cap">
                                </a>
                                <a href="{% url "frontend:singlepage" post.id %}" class="category-style">{{post.category}}</a>
                            </div>
                            <div class="title-wrap title-wrap-2">
                                <h4 class="title"><a href="#blog">{{post.title}}</a></h4>
                                <ul class="admin-list mt-2 mb-4" style="display:none !important;">
                                    <li><a href="#blog"><i class="far fa-user"></i>Patty Joe
                                        </a></li>
                                    <li><a href="#blog"><i class="far fa-heart"></i>18 Likes</a></li>
                                    <li><a href="#blog"><i class="far fa-comment-dots"></i>8 Comments</a>
                                    </li>
                                </ul>
                                <p>
                                    {{ post.description|slice:200 }}
                                    <a href ="{% url "frontend:singlepage" post.id %}" class="btn btn-style">Read More</a>

                                </p>
                            </div>
                        </div>
                        {% endfor %}

                    </div>
                </div>

                <div class="sidebar-side col-lg-4 pl-lg-5 mt-lg-0 mt-5">
                    <aside class="sidebar">
                        <!-- Popular Post Widget-->
                        <div class="sidebar-widget popular-posts">
                            <div class="sidebar-title">
                                <h4>Recent Posts</h4>
                            </div>
                            {% for post in recent_post %}
                             <article class="post">
                                <img src="{{post.image}}" alt="">
                                <div class="text"><a href="{% url "frontend:singlepage" post.id %}">{{ post.title }}</a>
                                    <div class="post-info">{{ post.publish|date:"d-m-Y" }}</div>
                                </div>
                            </article>
                            {% endfor %}

                           
                        </div>

                        <!-- Category Widget -->
                        <div class="sidebar-widget sidebar-blog-category">
                            <div class="sidebar-title">
                                <h4>Categories</h4>
                            </div>
                            
                            <ul class="blog-cat">
                                {%for item in categories %}
                                <li><a href="{% url "frontend:category" item.category %}">{{item.category}}
                                <label>{{item.category__count}}</label></a></li>
                                
                                {% endfor %}
                            </ul>
                        </div>

                        <!-- about Widget -->
                        <div class="sidebar-widget about-widget">
                            <div class="sidebar-title">
                                <h4>About Us</h4>
                            </div>
                            <div class="d-flex">
                                <div class="img-about-w3 mr-3">
                                    <img style="width:140px !important;height:100px !important" src="{{userinfo.user_photo.url}}" alt="" class="img-fluid"  />
                                </div>
                                <div class="right-ab-block">
                                    <h3>{{userinfo.username}}</h3>
                                    <p>{{userinfo.bio}}</p>
                                </div>
                            </div>
                        </div>

                        <!-- ads Widget -->
                        <div class="sidebar-widget">
                            <div class="sidebar-title">
                                <h4>Ads</h4>
                            </div>
                            <div class="ads-img-ab">
                                <a href="{{ads.ads_link}}">
                                    <img src="{{ads.ads_image.url}}" class="img-fluid" alt="" />
                                </a>
                            </div>
                        </div>
                        <!-- social media Widget-->
                        <div class="sidebar-widget social-style">
                            <div class="sidebar-title">
                                <h4>Social Media</h4>
                            </div>
                            {% for media in socialmedia %}
                            <a target="_blank" href="{{media.link}}"><i class="{{media.icons}}"></i>{{media.title}}</a>
                            {% endfor %}
                        </div>

                    </aside>
                </div>
            </div>
        </div>
    </section>
    <!-- //blog page -->

    <!-- subscribe section -->
    <section class="w3l-project pb-5" id="subscribe">
        <div class="container pb-4">
            <div class="bottom-info">
                <div class="header-section text-center">
                    <h3 class="title-style">Discover the most delicious recipes.</h3>
                    <p class="mt-3 pr-lg-5">Lorem ipsum dolor sit amet elit. Velit beatae
                        rem ullam dolore nisi esse quasi, sit amet. Lorem ipsum dolor sit
                        amet elit.</p>
                </div>
                <form id="newsletter_subscription" action="#" class="subscribe mt-5" method="post">
                    <div class="input-group-text"><i class="fas fa-paper-plane"></i></div>
                   {% csrf_token %}
                    <input type="email" required="" name="email" id="email" placeholder="Your Email Address" >
                    <button class="newsletterbtn" type="submit"  class="btn btn-style">Subscibe</button>
                    <div class="msg">

                    </div>
                </form>
            </div>
        </div>
    </section>
 

    <!-- footer -->
   {% include 'frontend/footer.html' %}
    <!-- //footer -->

    <!-- Js scripts -->
    <!-- move top -->
    <button onclick="topFunction()" id="movetop" title="Go to top">
        <span class="fas fa-level-up-alt" aria-hidden="true"></span>
    </button>
    {% include 'frontend/footerscript.html' %}
</body>

</html>

templates/frontend/navigation.html
<!--header-->
    <header id="site-header" class="fixed-top">
        <div class="container">
            <nav class="navbar navbar-expand-lg stroke">
                <h1>
                    <a class="navbar-brand" >
                       {{bloginfo.blog_title }}<i class="{{bloginfo.blog_icon}}"></i>
                    </a>
                </h1>
                <!-- if logo is image enable this   
    <a class="navbar-brand" href="#index.html">
        <img src="image-path" alt="Your logo" title="Your logo" style="height:35px;" />
    </a> -->
                <button class="navbar-toggler  collapsed bg-gradient" type="button" data-toggle="collapse"
                    data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon fa icon-expand fa-bars"></span>
                    <span class="navbar-toggler-icon fa icon-close fa-times"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                    <ul class="navbar-nav mx-lg-auto">
                        <li class="nav-item active ">
                          
                            <a class="nav-link" href="/">Home</a>
                              
                            
                        </li>
                        {% for link in navigation %}
                        <!--active-->
                       
                      
                        
                        <li class="nav-item  ">
                            <a class="nav-link"  href="{{link.link}}">{{ link.title }}
                                <span class="sr-only">(current)</span>
                            </a>
                        </li>
                        
                        {%  endfor %}
                    </ul>
                </div>
                <!-- search button -->
                <div class="search-right ml-lg-3">
                    <div class="search-container">
                        <form action="{% url 'frontend:search' %}" method="get" name="searchform" id="searchform" >

                            <input class="search expandright" id="searchright" type="search" name="q"
                                placeholder="Search">
                            <label class="button searchbutton" for="searchright"><i class="fas fa-search"></i></label>
                        </form>
                    </div>
                </div>
                <!-- //search button -->
                <!-- toggle switch for light and dark theme -->
                <div class="cont-ser-position">
                    <nav class="navigation">
                        <div class="theme-switch-wrapper" style="display:none !important;">
                            <label class="theme-switch" for="checkbox">
                                <input type="checkbox" id="checkbox">
                                <div class="mode-container">
                                    <i class="gg-sun"></i>
                                    <i class="gg-moon"></i>
                                </div>
                            </label>
                        </div>
                    </nav>
                </div>
                <!-- //toggle switch for light and dark theme -->
            </nav>
        </div>
    </header>
    <!--//header-->